export const FETCH_USER_PERMISSIONS_START = "FETCH_USER_PERMISSIONS_START";
export const FETCH_USER_PERMISSIONS_SUCCESS = "FETCH_USER_PERMISSIONS_SUCCESS";
export const FETCH_USER_PERMISSIONS_ERROR = "FETCH_USER_PERMISSIONS_ERROR";
