export const FETCH_USER_PRESCRIPTIONS_START = "FETCH_USER_PRESCRIPTIONS_START";
export const FETCH_USER_PRESCRIPTIONS_SUCCESS =
  "FETCH_USER_PRESCRIPTIONS_SUCCESS";
export const FETCH_USER_PRESCRIPTIONS_ERROR = "FETCH_USER_PRESCRIPTIONS_ERROR";
